#!/usr/bin/env bash
readonly KEY="$1";

rotate() {
	degree="$1"
	while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$KEY" in
    "C-c")
        tr '\n' ' ' | xsel -i ;;
    "C-d")
        while read file; do rm "$file"; done ;;
    "C-e")
        while read file; do urxvt -title scratchpad -geometry 80x20+40+60 -sl 0 -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
    "C-comma")
        rotate 270 ;;
    "C-period")
        rotate  90 ;;
    "C-slash")
        rotate 180 ;;
esac
