#!/usr/bin/env bash
case "$1" in
    "C-c")
        echo -n "$2" | xsel -i ;;
    "C-d")
        rm "$2" ;;
    "C-e")
        urxvt -title scratchpad -geometry 80x20+40+60 -e sh -c "exiv2 pr -q -pa '$2' | less" & ;;
esac
